//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VVSAssistant.Models
{
    using System;
    
    public enum ApplianceTypes : int
    {
        Heatpump = 0,
        Boiler = 1,
        TemperatureController = 2,
        SolarPanel = 3
    }
}
